### ISSUE TITLE
Not updated to 2.0

### ISSUE THREAD

**Issue by sud0n1m** [ccocchi/sass-twitter-bootstrap-rails#1]
I've heard of the legend of Ccocci. I wanted to use his work on a project, but it seems that his awesome sass-twitter-bootstrap-rails is only on bootstrap 1.4. It would be great to have it on 2.0.

**Comment by ccocchi** [comment]
It's coming soon (only because you asked nicely !)

**Comment by ccocchi** [comment]
And **voila** !
